before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

image: docker:19.03.8
services:
  - docker:19.03.8-dind

centos7:
  tags:
    - docker
  variables:
    tag: centos7
  script: &build
    - "docker build --pull -t $CI_REGISTRY/js947/spack-builder:$tag $tag"
    - "docker push $CI_REGISTRY/js947/spack-builder:$tag"

ubuntu18:
  tags:
    - docker
  variables:
    tag: ubuntu18
  script: *build

amazonlinux:
  tags:
    - docker
  variables:
    tag: amazonlinux
  script: *build
