before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

image: docker:19.03.8
services:
  - docker:19.03.8-dind

stages:
  - build
  - trigger

centos7:
  stage: build
  tags:
    - docker
  variables:
    tag: centos7
  script: &build
    - "docker build --pull -t $CI_REGISTRY/js947/spack-builder:$tag $tag"
    - "docker push $CI_REGISTRY/js947/spack-builder:$tag"

ubuntu18:
  stage: build
  tags:
    - docker
  variables:
    tag: ubuntu18
  script: *build

amazonlinux:
  stage: build
  tags:
    - docker
  variables:
    tag: amazonlinux
  script: *build

trigger:
  stage: trigger
  trigger: js947/fenics-build-mirror