name: Docker Image CI

on: [push, pull_request]

jobs:
  centos7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/centos7
        cache_froms: ${{ github.repository }}/centos7:latest
        dockerfile: images/centos7.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  centos8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/centos8
        cache_froms: ${{ github.repository }}/centos8:latest
        dockerfile: images/centos8.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  scientific7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/scientific7
        cache_froms: ${{ github.repository }}/scientific7:latest
        dockerfile: images/scientific7.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  amzn1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/amzn1
        cache_froms: ${{ github.repository }}/scientific7:latest
        dockerfile: images/amzn1.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  amzn2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/amzn2
        cache_froms: ${{ github.repository }}/amzn2:latest
        dockerfile: images/amzn2.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  ubuntu18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/ubuntu18
        cache_froms: ${{ github.repository }}/ubuntu18:latest
        dockerfile: images/ubuntu18.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images

  ubuntu20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/ubuntu20
        cache_froms: ${{ github.repository }}/ubuntu20:latest
        dockerfile: images/ubuntu20.Dockerfile
        tag_with_ref: true
        always_pull: true
        path: images
